name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      # - name: run db
      #   run: docker run -d --name db -p 5432:5432 -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -v db:/var/lib/postgresql/data postgres:16-alpine

      # client
      - name: stop client container
        run: docker stop tune-c
        continue-on-error: true

      - name: remove client container
        run: docker rm tune-c
        continue-on-error: true

      - name: remove client image
        run: docker rmi tune-client-production
        continue-on-error: true

      - name: build client
        run: docker build -t tune-client-production -f ./client/Dockerfile.prod .

      - name: run client
        run: docker run -it -d --name tune-c -p 3000:3000 tune-client-production

        # music sevice
      - name: stop music-service container
        run: docker stop tune-ms
        continue-on-error: true

      - name: remove music-service container
        run: docker rm tune-ms
        continue-on-error: true

      - name: remove music-service image
        run: docker rmi tune-ms-production
        continue-on-error: true

      - name: build music-service
        run: docker build -t tune-ms-production -f ./music-service/Dockerfile.prod .

      - name: run music-service
        run: docker run -it -d --name tune-ms -p 8000:8000 tune-ms-production
