name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

        # network
      - name: create tune network
        run: docker network create tune
        continue-on-error: true

        # db
      # - name: run db
      #   run: docker run -d --name db -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" -v db:/var/lib/postgresql/data -p 5432:5432 postgres:16-alpine

      # - name: connect db to tune network
      #   run: docker network connect tune db

      # client
      - name: stop client container
        run: docker stop tune-c
        continue-on-error: true

      - name: remove client container
        run: docker rm tune-c
        continue-on-error: true

      - name: remove client image
        run: docker rmi tune-client-production
        continue-on-error: true

      - name: build client
        run: docker build -t tune-client-production -f ./client/Dockerfile.prod .
        build-args: |
          "GOOGLE_ID=${{ secrets.GOOGLE_ID }}"
          "GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}"
          "GOOGLE_ID=${{ secrets.GOOGLE_ID }}" 
          "OAUTH_GITHUB_ID=${{ secrets.OAUTH_GITHUB_ID }}" 
          "OAUTH_GITHUB_SECRET=${{ secrets.OAUTH_GITHUB_SECRET }}" 
          "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" 
          "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" 
          "DATABASE_URL=${{ secrets.DATABASE_URL }}" 
          "CLIENT_API_URL=${{ secrets.CLIENT_API_URL }}" 
          "MUSIC_SERVICE_API_URL=${{ secrets.MUSIC_SERVICE_API_URL }}"

      - name: run client
        run: docker run -it -d --name tune-c -p 3000:3000 tune-client-production

      - name: connect client to tune network
        run: docker network connect tune tune-c

      # music sevice
      - name: stop music-service container
        run: docker stop tune-ms
        continue-on-error: true

      - name: remove music-service container
        run: docker rm tune-ms
        continue-on-error: true

      - name: remove music-service image
        run: docker rmi tune-ms-production
        continue-on-error: true

      - name: build music-service
        run: docker build -t tune-ms-production -f ./music-service/Dockerfile.prod .

      - name: run music-service
        run: docker run -it -d --name tune-ms -p 8000:8000 -v audio:/app/src/audio tune-ms-production

      - name: connect music-service to tune network
        run: docker network connect tune tune-ms
